config/routes.rb
Rails.application.routes.draw do

  root "customers#index"

  resources :customers
  resources :book_details
  resources :authers
  resources :suppliers
  resources :reviews


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/auther.rb
class Auther < ApplicationRecord
  has_many :book_details
end

app/controllers/authers_controller.rb
class AuthersController < ApplicationController
  before_action :set_auther, only: %i[ show edit update destroy ]

  # GET /authers or /authers.json
  def index
    @authers = Auther.all
  end

  # GET /authers/1 or /authers/1.json
  def show
  end

  # GET /authers/new
  def new
    @auther = Auther.new
  end

  # GET /authers/1/edit
  def edit
  end

  # POST /authers or /authers.json
  def create
    @auther = Auther.new(auther_params)

    respond_to do |format|
      if @auther.save
        format.html { redirect_to @auther, notice: "Auther was successfully created." }
        format.json { render :show, status: :created, location: @auther }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auther.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authers/1 or /authers/1.json
  def update
    respond_to do |format|
      if @auther.update(auther_params)
        format.html { redirect_to @auther, notice: "Auther was successfully updated." }
        format.json { render :show, status: :ok, location: @auther }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auther.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authers/1 or /authers/1.json
  def destroy
    @auther.destroy
    respond_to do |format|
      format.html { redirect_to authers_url, notice: "Auther was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auther
      @auther = Auther.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auther_params
      params.require(:auther).permit(:first_name, :last_name, :title)
    end
end

app/helpers/authers_helper.rb
module AuthersHelper
end

app/views/authers/_form.html.erb
<%= form_with(model: auther) do |form| %>
  <% if auther.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auther.errors.count, "error") %> prohibited this auther from being saved:</h2>

      <ul>
        <% auther.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authers/edit.html.erb
<h1>Editing Auther</h1>

<%= render 'form', auther: @auther %>

<%= link_to 'Show', @auther %> |
<%= link_to 'Back', authers_path %>

app/views/authers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authers.each do |auther| %>
      <tr>
        <td><%= auther.first_name %></td>
        <td><%= auther.last_name %></td>
        <td><%= auther.title %></td>
        <td><%= link_to 'Show', auther %></td>
        <td><%= link_to 'Edit', edit_auther_path(auther) %></td>
        <td><%= link_to 'Destroy', auther, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auther', new_auther_path %>

app/views/authers/new.html.erb
<h1>New Auther</h1>

<%= render 'form', auther: @auther %>

<%= link_to 'Back', authers_path %>

app/views/authers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @auther.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @auther.last_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @auther.title %>
</p>

<%= link_to 'Edit', edit_auther_path(@auther) %> |
<%= link_to 'Back', authers_path %>