config/routes.rb
Rails.application.routes.draw do

  root "customers#index"

  resources :customers
  resources :book_details
  resources :authers
  resources :suppliers
  resources :reviews


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_detail.rb
class BookDetail < ApplicationRecord
  belongs_to :supplier
  belongs_to :auther
  has_many :review
end

app/controllers/book_details_controller.rb
class BookDetailsController < ApplicationController
  before_action :set_book_detail, only: %i[ show edit update destroy ]

  # GET /book_details or /book_details.json
  def index
    @book_details = BookDetail.all
  end

  # GET /book_details/1 or /book_details/1.json
  def show
  end

  # GET /book_details/new
  def new
    @book_detail = BookDetail.new
  end

  # GET /book_details/1/edit
  def edit
  end

  # POST /book_details or /book_details.json
  def create
    @book_detail = BookDetail.new(book_detail_params)

    respond_to do |format|
      if @book_detail.save
        format.html { redirect_to @book_detail, notice: "Book detail was successfully created." }
        format.json { render :show, status: :created, location: @book_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_details/1 or /book_details/1.json
  def update
    respond_to do |format|
      if @book_detail.update(book_detail_params)
        format.html { redirect_to @book_detail, notice: "Book detail was successfully updated." }
        format.json { render :show, status: :ok, location: @book_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_details/1 or /book_details/1.json
  def destroy
    @book_detail.destroy
    respond_to do |format|
      format.html { redirect_to book_details_url, notice: "Book detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_detail
      @book_detail = BookDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_detail_params
      params.require(:book_detail).permit(:title, :year_published, :price)
    end
end

app/helpers/book_details_helper.rb
module BookDetailsHelper
end

app/views/book_details/_form.html.erb
<%= form_with(model: book_detail) do |form| %>
  <% if book_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_detail.errors.count, "error") %> prohibited this book_detail from being saved:</h2>

      <ul>
        <% book_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.select :supplier_id, options_from_collection_for_select(supplier_id form.object.supplier_id), prompt: "-- Select supplier id --" %>
  </div>

  <div class="field">
    <%= form.label :auther_id%>
    <%= form.text_field :auther_id, options_from_collection_for_select(auther_id form.object.auther_id), prompt: "-- Select auther" %>
  </div>

  <div class="field">
    <%= form.label :year_published %>
    <%= form.number_field :year_published %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_details/edit.html.erb
<h1>Editing Book Detail</h1>

<%= render 'form', book_detail: @book_detail %>

<%= link_to 'Show', @book_detail %> |
<%= link_to 'Back', book_details_path %>

app/views/book_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Details</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year published</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_details.each do |book_detail| %>
      <tr>
        <td><%= book_detail.title %></td>
        <td><%= book_detail.year_published %></td>
        <td><%= book_detail.price %></td>
        <td><%= link_to 'Show', book_detail %></td>
        <td><%= link_to 'Edit', edit_book_detail_path(book_detail) %></td>
        <td><%= link_to 'Destroy', book_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Detail', new_book_detail_path %>
<%= link_to 'Auther', auther_path %>
<%= link_to 'supplier', supplier_path %>

app/views/book_details/new.html.erb
<h1>New Book Detail</h1>

<%= render 'form', book_detail: @book_detail %>

<%= link_to 'Back', book_details_path %>

app/views/book_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book_detail.title %>
</p>

<p>
  <strong>Year published:</strong>
  <%= @book_detail.year_published %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book_detail.price %>
</p>

<%= link_to 'Edit', edit_book_detail_path(@book_detail) %> |
<%= link_to 'Back', book_details_path %>